### ISSUE TITLE
(different) error when adding a confirmation to a form

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/activity-log-gravity-forms#103]
I tried to reproduce this with the latest update: https://wordpress.org/support/topic/fatal-error-wsal_sensor_gravity_forms/

1. I created a form
2. I added a confirmation
3. I got the below error
4. Confirmation is created
5. Event is recorded

But there is still the error - different than the one reported in the .org ticket:

![image](https://user-images.githubusercontent.com/3965050/202269467-cd96cd55-e704-4d80-9eb2-d33a82c32eed.png)

**Comment by DannyWPWS** [comment]
Noting, this is with the CURRENT release, not 4.4.3
