### ISSUE TITLE
With GF Extension + WPForms Extension active, links to forms dont work

### ISSUE THREAD

**Issue by DannyWPWS** [wpwhitesecurity/activity-log-gravity-forms#66]
Spotted during testing WSAL 4.2.2 + the "live" (wordpress.org) extentions, when I have both plugins active - all links which show a "view form in editor" links no longer work:

![image](https://user-images.githubusercontent.com/59394454/115723875-5442d080-a378-11eb-9d37-7ada8daaf6f2.png)

It affects both the GF and WPForms events and in all cases the source of the link shows no value for its href

**Comment by robert81** [comment]
Let's chedck this but do not spend a lot of time on it. As in the chances of having both Gravity Forms and WPforms installed and used together on the same website are very very slim.

**Comment by DannyWPWS** [comment]
Closing this up as with both extensions running now, in both the case of GF and WPForms the links work great
