### ISSUE TITLE
New event: An entry was edited

### ISSUE THREAD

**Issue by DannyWPWS** [wpwhitesecurity/activity-log-gravity-forms#68]
Suggested by a user https://secure.helpscout.net/conversation/1524878092/1575/

Lets add a new event to report when an entry (a form submission) is edited.

The GF docs are great so this shouldnt be a problem.

**Comment by robert81** [comment]
Indeed, let's add event ID 5717 - [more info](https://docs.google.com/spreadsheets/d/1xjO3E7GtsOMPHTfLyaurNeJqmJkRCRsleBSAhsicyXA/edit#gid=1446535160)

**Comment by robert81** [comment]
Event ID 5717 (entry was modified) is not firing when editing an entry
