### ISSUE TITLE
5716: Stop reporting of transient change/Ensure output it never an object

### ISSUE THREAD

**Issue by DannyWPWS** [wpwhitesecurity/activity-log-gravity-forms#70]
Reported by a user https://secure.helpscout.net/conversation/1646659096/3189?folderId=4248868

First of all the transient shouldnt be reported at all, and secondly the value is an entire object which should not be allowed to pass through as it causes the log viewer to crash/hang for the user

![image](https://user-images.githubusercontent.com/59394454/137708531-2c3a56de-d8ef-4cba-800e-deaa18c77c7b.png)

**Comment by robert81** [comment]
Indeed. However, I think @martinkrcho has already applied a fix (since this was reported) that limits the data displayed.

@DannyWPWS can you please check with @martinkrcho about this when it is time to work on this?

**Comment by martinkrcho** [comment]
We only apply the limit to the data when we pass it to the **Action Scheduler**. This does not apply if the data is written to the local database. We could only display first X characters and only show the entire value in the **Alert Data Inspector** (pop-up).

It would be similar to what we've done for the long URL for image uploades:
https://github.com/wpwhitesecurity/wp-security-audit-log-premium/issues/1435#issuecomment-968906578

**Comment by DannyWPWS** [comment]
Closing added in this PR https://github.com/wpwhitesecurity/activity-log-gravity-forms/pull/73
