### ISSUE TITLE
5710 (Starred/Unstarred) no longer working

### ISSUE THREAD

**Issue by DannyWPWS** [wpwhitesecurity/activity-log-gravity-forms#74]
Discovered when working on another issue (new event) - it looks like the filter we used has been removed in favour for a new "gform_post_update_entry_property" one which happens to be one im working with now

**Comment by DannyWPWS** [comment]
Also affects 5711

**Comment by DannyWPWS** [comment]
Closing added in this PR https://github.com/wpwhitesecurity/activity-log-gravity-forms/pull/73

**Comment by robert81** [comment]
5710 is now working, but it is not reporting the Entry's name: 

![Uploading image.png…]()
