### ISSUE TITLE
Event ID 5703 wrongly reported

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/activity-log-gravity-forms#77]
Whenever I create a new form (reporting event ID 5700 correctly) and I add some fields and save it, I am getting this event ID the first time:

![image](https://user-images.githubusercontent.com/3965050/158950780-e3168b37-e2c9-46ff-b3c0-73bbc928b408.png)

I do not understand what it is or if it should be there in the first place.

**Comment by DannyWPWS** [comment]
Ok so this is basically happening as when a new form is made, the user has the choice of a few things they can do for the submit button

![image](https://user-images.githubusercontent.com/59394454/159021501-e2c43ed1-231c-4549-aa62-dbcde16ab219.png)

Its not clear, but to get to this you have to click on the "submit" button itself which appears in the form builder!

Personally I think we should (even on the 1st time a form is made) as it is a user configurable area, it just happens to be one thats automatically added for you when a make a form - BUT, this is totally up to you. If you dont want to report it on a freshly made form it shouldnt be a problem to suppress it

**Comment by DannyWPWS** [comment]
We have decided to leave it as is it (all makes sense on closer inspection) - so closing this up
