### ISSUE TITLE
Fatal error when creating a new confirmation

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/activity-log-gravity-forms#97]
When I try to create a new confirmation on a form, upon clicking save I get this error:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function WSAL_Sensors_Gravity_Forms::trigger_event_if(), 2 passed in /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-content/plugins/activity-log-gravity-forms/wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php on line 936 and exactly 3 expected in /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-content/plugins/activity-log-gravity-forms/wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php:1493 Stack trace: #0 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-content/plugins/activity-log-gravity-forms/wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php(936): WSAL_Sensors_Gravity_Forms->trigger_event_if() #1 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-includes/class-wp-hook.php(309): WSAL_Sensors_Gravity_Forms->event_form_confirmation_saved() #2 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-includ in /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-content/plugins/activity-log-gravity-forms/wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php on line 1493

Issue originally reported here: https://wordpress.org/support/topic/fatal-error-wsal_sensor_gravity_forms/

**Comment by DannyWPWS** [comment]
Closing this up as its fixed and in develop
